### ISSUE TITLE
Application Loading and DB user Permission Denied error

### ISSUE THREAD

**Issue by TacitTactics** [deeztek/Hermes-Secure-Email-Gateway#54]
I am not sure what is breaking, but I have noticed a few things that stand out as issues. After logging into the application I get the following errors: 

```
Lucee 5.2.9.31 Error (application)
--
Message | Error invoking external process
Detail | /sys/firmware/dmi/tables/smbios_entry_point: Permission denied/dev/mem: No such file or directory
Stacktrace | The Error Occurred in/compile/proprietary/2/inc/setsession.cfm: line 1412: ?O13: doStartTagQ$14: ?RinitBody&(Ljavax/servlet/jsp/tagext/BodyTag;I)VTU15: /V16: XdoAfterBodyZ$called from /var/www/html/admin/Application.cfc: line 261
```

I also noticed that the Hermes user cannot access the DB:
`Aug 30 18:05:16 Hermes-SEG postfix/smtp[9692]: warning: connect to mysql server 127.0.0.1: Access denied for user 'hermes'@'localhost' (using password: YES)`

I was able to login with the DB user locally,  but the application fails to do so. This proves that the password works. 

I used the exact recommended setup for Ubuntu 20.04. It is running in a LXC container on ProxMox

**Comment by deeztek** [comment]
We have never ran Hermes on a LXC. I suspect that's the problem since it's not a full OS. If possible, please try to use a full Ubuntu vm to run Hermes. I don't know the specific caveats of LXC as related to Hermes. From the error you posted, it looks like it's missing some directories the system expects to find. In terms of the db, that's another issue which may or may not be related to LXC but there's no way to troubleshoot at this time.

**Comment by TacitTactics** [comment]
Ok,  I will try a VM instead, and update soon. Thank you for quick reply

**Comment by TacitTactics** [comment]
That did resolve the issue. Must be in physical or VM. No LXC Container.
